# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/Github/X-motor-Drive

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/Github/X-motor-Drive

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/Github/X-motor-Drive/CMakeFiles /data/Github/X-motor-Drive//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/Github/X-motor-Drive/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named XDr

# Build rule for target.
XDr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 XDr
.PHONY : XDr

# fast build rule for target.
XDr/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/build
.PHONY : XDr/fast

#=============================================================================
# Target rules for targets named stm32_hal

# Build rule for target.
stm32_hal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stm32_hal
.PHONY : stm32_hal

# fast build rule for target.
stm32_hal/fast:
	$(MAKE) $(MAKESILENT) -f board/xdr_p_o1.2/CMakeFiles/stm32_hal.dir/build.make board/xdr_p_o1.2/CMakeFiles/stm32_hal.dir/build
.PHONY : stm32_hal/fast

#=============================================================================
# Target rules for targets named stm32_core

# Build rule for target.
stm32_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stm32_core
.PHONY : stm32_core

# fast build rule for target.
stm32_core/fast:
	$(MAKE) $(MAKESILENT) -f board/xdr_p_o1.2/CMakeFiles/stm32_core.dir/build.make board/xdr_p_o1.2/CMakeFiles/stm32_core.dir/build
.PHONY : stm32_core/fast

#=============================================================================
# Target rules for targets named stm32_usb

# Build rule for target.
stm32_usb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stm32_usb
.PHONY : stm32_usb

# fast build rule for target.
stm32_usb/fast:
	$(MAKE) $(MAKESILENT) -f board/xdr_p_o1.2/CMakeFiles/stm32_usb.dir/build.make board/xdr_p_o1.2/CMakeFiles/stm32_usb.dir/build
.PHONY : stm32_usb/fast

#=============================================================================
# Target rules for targets named board_bsp

# Build rule for target.
board_bsp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 board_bsp
.PHONY : board_bsp

# fast build rule for target.
board_bsp/fast:
	$(MAKE) $(MAKESILENT) -f board/xdr_p_o1.2/CMakeFiles/board_bsp.dir/build.make board/xdr_p_o1.2/CMakeFiles/board_bsp.dir/build
.PHONY : board_bsp/fast

app/app_main.o: app/app_main.c.o
.PHONY : app/app_main.o

# target to build an object file
app/app_main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/app_main.c.o
.PHONY : app/app_main.c.o

app/app_main.i: app/app_main.c.i
.PHONY : app/app_main.i

# target to preprocess a source file
app/app_main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/app_main.c.i
.PHONY : app/app_main.c.i

app/app_main.s: app/app_main.c.s
.PHONY : app/app_main.s

# target to generate assembly for a file
app/app_main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/app_main.c.s
.PHONY : app/app_main.c.s

app/communication/DataMonitoring.o: app/communication/DataMonitoring.c.o
.PHONY : app/communication/DataMonitoring.o

# target to build an object file
app/communication/DataMonitoring.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/communication/DataMonitoring.c.o
.PHONY : app/communication/DataMonitoring.c.o

app/communication/DataMonitoring.i: app/communication/DataMonitoring.c.i
.PHONY : app/communication/DataMonitoring.i

# target to preprocess a source file
app/communication/DataMonitoring.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/communication/DataMonitoring.c.i
.PHONY : app/communication/DataMonitoring.c.i

app/communication/DataMonitoring.s: app/communication/DataMonitoring.c.s
.PHONY : app/communication/DataMonitoring.s

# target to generate assembly for a file
app/communication/DataMonitoring.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/communication/DataMonitoring.c.s
.PHONY : app/communication/DataMonitoring.c.s

app/communication/can_port.o: app/communication/can_port.c.o
.PHONY : app/communication/can_port.o

# target to build an object file
app/communication/can_port.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/communication/can_port.c.o
.PHONY : app/communication/can_port.c.o

app/communication/can_port.i: app/communication/can_port.c.i
.PHONY : app/communication/can_port.i

# target to preprocess a source file
app/communication/can_port.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/communication/can_port.c.i
.PHONY : app/communication/can_port.c.i

app/communication/can_port.s: app/communication/can_port.c.s
.PHONY : app/communication/can_port.s

# target to generate assembly for a file
app/communication/can_port.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/communication/can_port.c.s
.PHONY : app/communication/can_port.c.s

app/communication/port_mapping.o: app/communication/port_mapping.c.o
.PHONY : app/communication/port_mapping.o

# target to build an object file
app/communication/port_mapping.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/communication/port_mapping.c.o
.PHONY : app/communication/port_mapping.c.o

app/communication/port_mapping.i: app/communication/port_mapping.c.i
.PHONY : app/communication/port_mapping.i

# target to preprocess a source file
app/communication/port_mapping.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/communication/port_mapping.c.i
.PHONY : app/communication/port_mapping.c.i

app/communication/port_mapping.s: app/communication/port_mapping.c.s
.PHONY : app/communication/port_mapping.s

# target to generate assembly for a file
app/communication/port_mapping.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/communication/port_mapping.c.s
.PHONY : app/communication/port_mapping.c.s

app/communication/uart_port.o: app/communication/uart_port.c.o
.PHONY : app/communication/uart_port.o

# target to build an object file
app/communication/uart_port.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/communication/uart_port.c.o
.PHONY : app/communication/uart_port.c.o

app/communication/uart_port.i: app/communication/uart_port.c.i
.PHONY : app/communication/uart_port.i

# target to preprocess a source file
app/communication/uart_port.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/communication/uart_port.c.i
.PHONY : app/communication/uart_port.c.i

app/communication/uart_port.s: app/communication/uart_port.c.s
.PHONY : app/communication/uart_port.s

# target to generate assembly for a file
app/communication/uart_port.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/communication/uart_port.c.s
.PHONY : app/communication/uart_port.c.s

app/communication/usb_port.o: app/communication/usb_port.c.o
.PHONY : app/communication/usb_port.o

# target to build an object file
app/communication/usb_port.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/communication/usb_port.c.o
.PHONY : app/communication/usb_port.c.o

app/communication/usb_port.i: app/communication/usb_port.c.i
.PHONY : app/communication/usb_port.i

# target to preprocess a source file
app/communication/usb_port.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/communication/usb_port.c.i
.PHONY : app/communication/usb_port.c.i

app/communication/usb_port.s: app/communication/usb_port.c.s
.PHONY : app/communication/usb_port.s

# target to generate assembly for a file
app/communication/usb_port.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/communication/usb_port.c.s
.PHONY : app/communication/usb_port.c.s

app/control/foc_core.o: app/control/foc_core.c.o
.PHONY : app/control/foc_core.o

# target to build an object file
app/control/foc_core.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/foc_core.c.o
.PHONY : app/control/foc_core.c.o

app/control/foc_core.i: app/control/foc_core.c.i
.PHONY : app/control/foc_core.i

# target to preprocess a source file
app/control/foc_core.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/foc_core.c.i
.PHONY : app/control/foc_core.c.i

app/control/foc_core.s: app/control/foc_core.c.s
.PHONY : app/control/foc_core.s

# target to generate assembly for a file
app/control/foc_core.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/foc_core.c.s
.PHONY : app/control/foc_core.c.s

app/control/foc_main.o: app/control/foc_main.c.o
.PHONY : app/control/foc_main.o

# target to build an object file
app/control/foc_main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/foc_main.c.o
.PHONY : app/control/foc_main.c.o

app/control/foc_main.i: app/control/foc_main.c.i
.PHONY : app/control/foc_main.i

# target to preprocess a source file
app/control/foc_main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/foc_main.c.i
.PHONY : app/control/foc_main.c.i

app/control/foc_main.s: app/control/foc_main.c.s
.PHONY : app/control/foc_main.s

# target to generate assembly for a file
app/control/foc_main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/foc_main.c.s
.PHONY : app/control/foc_main.c.s

app/control/hfi.o: app/control/hfi.c.o
.PHONY : app/control/hfi.o

# target to build an object file
app/control/hfi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/hfi.c.o
.PHONY : app/control/hfi.c.o

app/control/hfi.i: app/control/hfi.c.i
.PHONY : app/control/hfi.i

# target to preprocess a source file
app/control/hfi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/hfi.c.i
.PHONY : app/control/hfi.c.i

app/control/hfi.s: app/control/hfi.c.s
.PHONY : app/control/hfi.s

# target to generate assembly for a file
app/control/hfi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/hfi.c.s
.PHONY : app/control/hfi.c.s

app/control/loop_control.o: app/control/loop_control.c.o
.PHONY : app/control/loop_control.o

# target to build an object file
app/control/loop_control.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/loop_control.c.o
.PHONY : app/control/loop_control.c.o

app/control/loop_control.i: app/control/loop_control.c.i
.PHONY : app/control/loop_control.i

# target to preprocess a source file
app/control/loop_control.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/loop_control.c.i
.PHONY : app/control/loop_control.c.i

app/control/loop_control.s: app/control/loop_control.c.s
.PHONY : app/control/loop_control.s

# target to generate assembly for a file
app/control/loop_control.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/loop_control.c.s
.PHONY : app/control/loop_control.c.s

app/control/mit.o: app/control/mit.c.o
.PHONY : app/control/mit.o

# target to build an object file
app/control/mit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/mit.c.o
.PHONY : app/control/mit.c.o

app/control/mit.i: app/control/mit.c.i
.PHONY : app/control/mit.i

# target to preprocess a source file
app/control/mit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/mit.c.i
.PHONY : app/control/mit.c.i

app/control/mit.s: app/control/mit.c.s
.PHONY : app/control/mit.s

# target to generate assembly for a file
app/control/mit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/mit.c.s
.PHONY : app/control/mit.c.s

app/control/smo.o: app/control/smo.c.o
.PHONY : app/control/smo.o

# target to build an object file
app/control/smo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/smo.c.o
.PHONY : app/control/smo.c.o

app/control/smo.i: app/control/smo.c.i
.PHONY : app/control/smo.i

# target to preprocess a source file
app/control/smo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/smo.c.i
.PHONY : app/control/smo.c.i

app/control/smo.s: app/control/smo.c.s
.PHONY : app/control/smo.s

# target to generate assembly for a file
app/control/smo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/smo.c.s
.PHONY : app/control/smo.c.s

app/control/svpwm.o: app/control/svpwm.c.o
.PHONY : app/control/svpwm.o

# target to build an object file
app/control/svpwm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/svpwm.c.o
.PHONY : app/control/svpwm.c.o

app/control/svpwm.i: app/control/svpwm.c.i
.PHONY : app/control/svpwm.i

# target to preprocess a source file
app/control/svpwm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/svpwm.c.i
.PHONY : app/control/svpwm.c.i

app/control/svpwm.s: app/control/svpwm.c.s
.PHONY : app/control/svpwm.s

# target to generate assembly for a file
app/control/svpwm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/svpwm.c.s
.PHONY : app/control/svpwm.c.s

app/control/tune.o: app/control/tune.c.o
.PHONY : app/control/tune.o

# target to build an object file
app/control/tune.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/tune.c.o
.PHONY : app/control/tune.c.o

app/control/tune.i: app/control/tune.c.i
.PHONY : app/control/tune.i

# target to preprocess a source file
app/control/tune.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/tune.c.i
.PHONY : app/control/tune.c.i

app/control/tune.s: app/control/tune.c.s
.PHONY : app/control/tune.s

# target to generate assembly for a file
app/control/tune.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/control/tune.c.s
.PHONY : app/control/tune.c.s

app/drivers/encoder.o: app/drivers/encoder.c.o
.PHONY : app/drivers/encoder.o

# target to build an object file
app/drivers/encoder.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/drivers/encoder.c.o
.PHONY : app/drivers/encoder.c.o

app/drivers/encoder.i: app/drivers/encoder.c.i
.PHONY : app/drivers/encoder.i

# target to preprocess a source file
app/drivers/encoder.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/drivers/encoder.c.i
.PHONY : app/drivers/encoder.c.i

app/drivers/encoder.s: app/drivers/encoder.c.s
.PHONY : app/drivers/encoder.s

# target to generate assembly for a file
app/drivers/encoder.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/drivers/encoder.c.s
.PHONY : app/drivers/encoder.c.s

app/drivers/flashDr.o: app/drivers/flashDr.c.o
.PHONY : app/drivers/flashDr.o

# target to build an object file
app/drivers/flashDr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/drivers/flashDr.c.o
.PHONY : app/drivers/flashDr.c.o

app/drivers/flashDr.i: app/drivers/flashDr.c.i
.PHONY : app/drivers/flashDr.i

# target to preprocess a source file
app/drivers/flashDr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/drivers/flashDr.c.i
.PHONY : app/drivers/flashDr.c.i

app/drivers/flashDr.s: app/drivers/flashDr.c.s
.PHONY : app/drivers/flashDr.s

# target to generate assembly for a file
app/drivers/flashDr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/drivers/flashDr.c.s
.PHONY : app/drivers/flashDr.c.s

app/drivers/led.o: app/drivers/led.c.o
.PHONY : app/drivers/led.o

# target to build an object file
app/drivers/led.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/drivers/led.c.o
.PHONY : app/drivers/led.c.o

app/drivers/led.i: app/drivers/led.c.i
.PHONY : app/drivers/led.i

# target to preprocess a source file
app/drivers/led.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/drivers/led.c.i
.PHONY : app/drivers/led.c.i

app/drivers/led.s: app/drivers/led.c.s
.PHONY : app/drivers/led.s

# target to generate assembly for a file
app/drivers/led.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/drivers/led.c.s
.PHONY : app/drivers/led.c.s

app/services/log.o: app/services/log.c.o
.PHONY : app/services/log.o

# target to build an object file
app/services/log.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/services/log.c.o
.PHONY : app/services/log.c.o

app/services/log.i: app/services/log.c.i
.PHONY : app/services/log.i

# target to preprocess a source file
app/services/log.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/services/log.c.i
.PHONY : app/services/log.c.i

app/services/log.s: app/services/log.c.s
.PHONY : app/services/log.s

# target to generate assembly for a file
app/services/log.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/services/log.c.s
.PHONY : app/services/log.c.s

app/services/parameter_manager.o: app/services/parameter_manager.c.o
.PHONY : app/services/parameter_manager.o

# target to build an object file
app/services/parameter_manager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/services/parameter_manager.c.o
.PHONY : app/services/parameter_manager.c.o

app/services/parameter_manager.i: app/services/parameter_manager.c.i
.PHONY : app/services/parameter_manager.i

# target to preprocess a source file
app/services/parameter_manager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/services/parameter_manager.c.i
.PHONY : app/services/parameter_manager.c.i

app/services/parameter_manager.s: app/services/parameter_manager.c.s
.PHONY : app/services/parameter_manager.s

# target to generate assembly for a file
app/services/parameter_manager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/services/parameter_manager.c.s
.PHONY : app/services/parameter_manager.c.s

app/services/protection_manager.o: app/services/protection_manager.c.o
.PHONY : app/services/protection_manager.o

# target to build an object file
app/services/protection_manager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/services/protection_manager.c.o
.PHONY : app/services/protection_manager.c.o

app/services/protection_manager.i: app/services/protection_manager.c.i
.PHONY : app/services/protection_manager.i

# target to preprocess a source file
app/services/protection_manager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/services/protection_manager.c.i
.PHONY : app/services/protection_manager.c.i

app/services/protection_manager.s: app/services/protection_manager.c.s
.PHONY : app/services/protection_manager.s

# target to generate assembly for a file
app/services/protection_manager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/services/protection_manager.c.s
.PHONY : app/services/protection_manager.c.s

app/services/status_feedback.o: app/services/status_feedback.c.o
.PHONY : app/services/status_feedback.o

# target to build an object file
app/services/status_feedback.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/services/status_feedback.c.o
.PHONY : app/services/status_feedback.c.o

app/services/status_feedback.i: app/services/status_feedback.c.i
.PHONY : app/services/status_feedback.i

# target to preprocess a source file
app/services/status_feedback.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/services/status_feedback.c.i
.PHONY : app/services/status_feedback.c.i

app/services/status_feedback.s: app/services/status_feedback.c.s
.PHONY : app/services/status_feedback.s

# target to generate assembly for a file
app/services/status_feedback.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/services/status_feedback.c.s
.PHONY : app/services/status_feedback.c.s

app/utils/filter.o: app/utils/filter.c.o
.PHONY : app/utils/filter.o

# target to build an object file
app/utils/filter.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/utils/filter.c.o
.PHONY : app/utils/filter.c.o

app/utils/filter.i: app/utils/filter.c.i
.PHONY : app/utils/filter.i

# target to preprocess a source file
app/utils/filter.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/utils/filter.c.i
.PHONY : app/utils/filter.c.i

app/utils/filter.s: app/utils/filter.c.s
.PHONY : app/utils/filter.s

# target to generate assembly for a file
app/utils/filter.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/utils/filter.c.s
.PHONY : app/utils/filter.c.s

app/utils/math_fast.o: app/utils/math_fast.c.o
.PHONY : app/utils/math_fast.o

# target to build an object file
app/utils/math_fast.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/utils/math_fast.c.o
.PHONY : app/utils/math_fast.c.o

app/utils/math_fast.i: app/utils/math_fast.c.i
.PHONY : app/utils/math_fast.i

# target to preprocess a source file
app/utils/math_fast.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/utils/math_fast.c.i
.PHONY : app/utils/math_fast.c.i

app/utils/math_fast.s: app/utils/math_fast.c.s
.PHONY : app/utils/math_fast.s

# target to generate assembly for a file
app/utils/math_fast.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/utils/math_fast.c.s
.PHONY : app/utils/math_fast.c.s

app/utils/queue.o: app/utils/queue.c.o
.PHONY : app/utils/queue.o

# target to build an object file
app/utils/queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/utils/queue.c.o
.PHONY : app/utils/queue.c.o

app/utils/queue.i: app/utils/queue.c.i
.PHONY : app/utils/queue.i

# target to preprocess a source file
app/utils/queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/utils/queue.c.i
.PHONY : app/utils/queue.c.i

app/utils/queue.s: app/utils/queue.c.s
.PHONY : app/utils/queue.s

# target to generate assembly for a file
app/utils/queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/utils/queue.c.s
.PHONY : app/utils/queue.c.s

app/utils/trajectory.o: app/utils/trajectory.c.o
.PHONY : app/utils/trajectory.o

# target to build an object file
app/utils/trajectory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/utils/trajectory.c.o
.PHONY : app/utils/trajectory.c.o

app/utils/trajectory.i: app/utils/trajectory.c.i
.PHONY : app/utils/trajectory.i

# target to preprocess a source file
app/utils/trajectory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/utils/trajectory.c.i
.PHONY : app/utils/trajectory.c.i

app/utils/trajectory.s: app/utils/trajectory.c.s
.PHONY : app/utils/trajectory.s

# target to generate assembly for a file
app/utils/trajectory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/app/utils/trajectory.c.s
.PHONY : app/utils/trajectory.c.s

board/xdr_p_o1.2/Core/Src/main.o: board/xdr_p_o1.2/Core/Src/main.c.o
.PHONY : board/xdr_p_o1.2/Core/Src/main.o

# target to build an object file
board/xdr_p_o1.2/Core/Src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/board/xdr_p_o1.2/Core/Src/main.c.o
.PHONY : board/xdr_p_o1.2/Core/Src/main.c.o

board/xdr_p_o1.2/Core/Src/main.i: board/xdr_p_o1.2/Core/Src/main.c.i
.PHONY : board/xdr_p_o1.2/Core/Src/main.i

# target to preprocess a source file
board/xdr_p_o1.2/Core/Src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/board/xdr_p_o1.2/Core/Src/main.c.i
.PHONY : board/xdr_p_o1.2/Core/Src/main.c.i

board/xdr_p_o1.2/Core/Src/main.s: board/xdr_p_o1.2/Core/Src/main.c.s
.PHONY : board/xdr_p_o1.2/Core/Src/main.s

# target to generate assembly for a file
board/xdr_p_o1.2/Core/Src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/board/xdr_p_o1.2/Core/Src/main.c.s
.PHONY : board/xdr_p_o1.2/Core/Src/main.c.s

board/xdr_p_o1.2/Core/Src/stm32f4xx_it.o: board/xdr_p_o1.2/Core/Src/stm32f4xx_it.c.o
.PHONY : board/xdr_p_o1.2/Core/Src/stm32f4xx_it.o

# target to build an object file
board/xdr_p_o1.2/Core/Src/stm32f4xx_it.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/board/xdr_p_o1.2/Core/Src/stm32f4xx_it.c.o
.PHONY : board/xdr_p_o1.2/Core/Src/stm32f4xx_it.c.o

board/xdr_p_o1.2/Core/Src/stm32f4xx_it.i: board/xdr_p_o1.2/Core/Src/stm32f4xx_it.c.i
.PHONY : board/xdr_p_o1.2/Core/Src/stm32f4xx_it.i

# target to preprocess a source file
board/xdr_p_o1.2/Core/Src/stm32f4xx_it.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/board/xdr_p_o1.2/Core/Src/stm32f4xx_it.c.i
.PHONY : board/xdr_p_o1.2/Core/Src/stm32f4xx_it.c.i

board/xdr_p_o1.2/Core/Src/stm32f4xx_it.s: board/xdr_p_o1.2/Core/Src/stm32f4xx_it.c.s
.PHONY : board/xdr_p_o1.2/Core/Src/stm32f4xx_it.s

# target to generate assembly for a file
board/xdr_p_o1.2/Core/Src/stm32f4xx_it.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/board/xdr_p_o1.2/Core/Src/stm32f4xx_it.c.s
.PHONY : board/xdr_p_o1.2/Core/Src/stm32f4xx_it.c.s

board/xdr_p_o1.2/Core/Src/syscalls.o: board/xdr_p_o1.2/Core/Src/syscalls.c.o
.PHONY : board/xdr_p_o1.2/Core/Src/syscalls.o

# target to build an object file
board/xdr_p_o1.2/Core/Src/syscalls.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/board/xdr_p_o1.2/Core/Src/syscalls.c.o
.PHONY : board/xdr_p_o1.2/Core/Src/syscalls.c.o

board/xdr_p_o1.2/Core/Src/syscalls.i: board/xdr_p_o1.2/Core/Src/syscalls.c.i
.PHONY : board/xdr_p_o1.2/Core/Src/syscalls.i

# target to preprocess a source file
board/xdr_p_o1.2/Core/Src/syscalls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/board/xdr_p_o1.2/Core/Src/syscalls.c.i
.PHONY : board/xdr_p_o1.2/Core/Src/syscalls.c.i

board/xdr_p_o1.2/Core/Src/syscalls.s: board/xdr_p_o1.2/Core/Src/syscalls.c.s
.PHONY : board/xdr_p_o1.2/Core/Src/syscalls.s

# target to generate assembly for a file
board/xdr_p_o1.2/Core/Src/syscalls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/board/xdr_p_o1.2/Core/Src/syscalls.c.s
.PHONY : board/xdr_p_o1.2/Core/Src/syscalls.c.s

board/xdr_p_o1.2/startup_stm32f405xx.o: board/xdr_p_o1.2/startup_stm32f405xx.s.o
.PHONY : board/xdr_p_o1.2/startup_stm32f405xx.o

# target to build an object file
board/xdr_p_o1.2/startup_stm32f405xx.s.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/XDr.dir/build.make CMakeFiles/XDr.dir/board/xdr_p_o1.2/startup_stm32f405xx.s.o
.PHONY : board/xdr_p_o1.2/startup_stm32f405xx.s.o

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... XDr"
	@echo "... board_bsp"
	@echo "... stm32_core"
	@echo "... stm32_hal"
	@echo "... stm32_usb"
	@echo "... app/app_main.o"
	@echo "... app/app_main.i"
	@echo "... app/app_main.s"
	@echo "... app/communication/DataMonitoring.o"
	@echo "... app/communication/DataMonitoring.i"
	@echo "... app/communication/DataMonitoring.s"
	@echo "... app/communication/can_port.o"
	@echo "... app/communication/can_port.i"
	@echo "... app/communication/can_port.s"
	@echo "... app/communication/port_mapping.o"
	@echo "... app/communication/port_mapping.i"
	@echo "... app/communication/port_mapping.s"
	@echo "... app/communication/uart_port.o"
	@echo "... app/communication/uart_port.i"
	@echo "... app/communication/uart_port.s"
	@echo "... app/communication/usb_port.o"
	@echo "... app/communication/usb_port.i"
	@echo "... app/communication/usb_port.s"
	@echo "... app/control/foc_core.o"
	@echo "... app/control/foc_core.i"
	@echo "... app/control/foc_core.s"
	@echo "... app/control/foc_main.o"
	@echo "... app/control/foc_main.i"
	@echo "... app/control/foc_main.s"
	@echo "... app/control/hfi.o"
	@echo "... app/control/hfi.i"
	@echo "... app/control/hfi.s"
	@echo "... app/control/loop_control.o"
	@echo "... app/control/loop_control.i"
	@echo "... app/control/loop_control.s"
	@echo "... app/control/mit.o"
	@echo "... app/control/mit.i"
	@echo "... app/control/mit.s"
	@echo "... app/control/smo.o"
	@echo "... app/control/smo.i"
	@echo "... app/control/smo.s"
	@echo "... app/control/svpwm.o"
	@echo "... app/control/svpwm.i"
	@echo "... app/control/svpwm.s"
	@echo "... app/control/tune.o"
	@echo "... app/control/tune.i"
	@echo "... app/control/tune.s"
	@echo "... app/drivers/encoder.o"
	@echo "... app/drivers/encoder.i"
	@echo "... app/drivers/encoder.s"
	@echo "... app/drivers/flashDr.o"
	@echo "... app/drivers/flashDr.i"
	@echo "... app/drivers/flashDr.s"
	@echo "... app/drivers/led.o"
	@echo "... app/drivers/led.i"
	@echo "... app/drivers/led.s"
	@echo "... app/services/log.o"
	@echo "... app/services/log.i"
	@echo "... app/services/log.s"
	@echo "... app/services/parameter_manager.o"
	@echo "... app/services/parameter_manager.i"
	@echo "... app/services/parameter_manager.s"
	@echo "... app/services/protection_manager.o"
	@echo "... app/services/protection_manager.i"
	@echo "... app/services/protection_manager.s"
	@echo "... app/services/status_feedback.o"
	@echo "... app/services/status_feedback.i"
	@echo "... app/services/status_feedback.s"
	@echo "... app/utils/filter.o"
	@echo "... app/utils/filter.i"
	@echo "... app/utils/filter.s"
	@echo "... app/utils/math_fast.o"
	@echo "... app/utils/math_fast.i"
	@echo "... app/utils/math_fast.s"
	@echo "... app/utils/queue.o"
	@echo "... app/utils/queue.i"
	@echo "... app/utils/queue.s"
	@echo "... app/utils/trajectory.o"
	@echo "... app/utils/trajectory.i"
	@echo "... app/utils/trajectory.s"
	@echo "... board/xdr_p_o1.2/Core/Src/main.o"
	@echo "... board/xdr_p_o1.2/Core/Src/main.i"
	@echo "... board/xdr_p_o1.2/Core/Src/main.s"
	@echo "... board/xdr_p_o1.2/Core/Src/stm32f4xx_it.o"
	@echo "... board/xdr_p_o1.2/Core/Src/stm32f4xx_it.i"
	@echo "... board/xdr_p_o1.2/Core/Src/stm32f4xx_it.s"
	@echo "... board/xdr_p_o1.2/Core/Src/syscalls.o"
	@echo "... board/xdr_p_o1.2/Core/Src/syscalls.i"
	@echo "... board/xdr_p_o1.2/Core/Src/syscalls.s"
	@echo "... board/xdr_p_o1.2/startup_stm32f405xx.o"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

