#ifndef USB_PROTOCOL_H
#define USB_PROTOCOL_H

/*usbd_desc.h*/
/*
#define USBD_VID 1155
#define USBD_LANGID_STRING 1033
#define USBD_MANUFACTURER_STRING "STMicroelectronics"
#define USBD_PID_FS 22336
#define USBD_PRODUCT_STRING_FS "XDrive"
#define USBD_CONFIGURATION_STRING_FS "CDC Config"
#define USBD_INTERFACE_STRING_FS "CDC Interface"

#define USB_SIZ_BOS_DESC 0x0C
*/
#define USB_PACKET_HEAD 0x2C
#define USB_PACKET_TAIL 0xC2
#define USB_PACKET_MAX_SIZE 256

#endif // USB_PROTOCOL_H